### PR TITLE
paypal-resto-sdk 1.5.2

### PR DESCRIPTION
**Pull request by paulomcnally**
Update paypal-rest-sdk version to 1.5.2. Need for work with node.js 0.12.x

### CODE REVIEW

**Comment by grawk** [comment]
backwards compatible to 0.10?

**Comment by paulomcnally** [comment]
Yes!

v0.10.30 work

**Comment by aredridel** [comment]
API is otherwise compatible with 0.6.x?

**Comment by paulomcnally** [comment]
With 0.6.x:

```
[development] Listening on http://localhost:8000
db connection open
::1 - - [28/Apr/2015:22:51:59 +0000] "GET / HTTP/1.1" 200 1627 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
express deprecated req.param(name): Use req.params, req.body, or req.query instead controllers/cart/index.js:56:16
::1 - - [28/Apr/2015:22:52:00 +0000] "POST /cart HTTP/1.1" 302 66 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
::1 - - [28/Apr/2015:22:52:00 +0000] "GET /cart HTTP/1.1" 200 1896 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
express deprecated req.param(name): Use req.params, req.body, or req.query instead controllers/pay/index.js:14:16
express deprecated req.param(name): Use req.params, req.body, or req.query instead controllers/pay/index.js:15:23
express deprecated req.param(name): Use req.params, req.body, or req.query instead controllers/pay/index.js:16:22
express deprecated req.param(name): Use req.params, req.body, or req.query instead controllers/pay/index.js:17:22
express deprecated req.param(name): Use req.params, req.body, or req.query instead controllers/pay/index.js:18:21
express deprecated req.param(name): Use req.params, req.body, or req.query instead controllers/pay/index.js:19:17
Tue, 28 Apr 2015 22:52:04 GMT uncaughtException Cannot assign to read only property 'httpStatusCode' of {"scope":"https://uri.paypal.com/services/invoicing openid https://api.paypal.com/v1/developer/.* https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card/.* https://api.paypal.com/v1/vault/credit-card","access_token":"A0156WT7LWs-lDRgoY1MpiySXj7NeGyVlr5aTTsJea.eMfs","token_type":"Bearer","app_id":"APP-2EJ531395M785864S","expires_in":28800}
TypeError: Cannot assign to read only property 'httpStatusCode' of {"scope":"https://uri.paypal.com/services/invoicing openid https://api.paypal.com/v1/developer/.* https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card/.* https://api.paypal.com/v1/vault/credit-card","access_token":"A0156WT7LWs-lDRgoY1MpiySXj7NeGyVlr5aTTsJea.eMfs","token_type":"Bearer","app_id":"APP-2EJ531395M785864S","expires_in":28800}
    at IncomingMessage.<anonymous> (/Users/paulomcnally/develop/test/kraken-example-with-shoppingcart/node_modules/paypal-rest-sdk/lib/paypal-rest-sdk.js:208:41)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by grawk** [comment]
`kraken-js@0.7` lists node as `>=0.10` in package.json. Is it necessary that we even document incompatibilities going as far back as `node@0.6`?

**Comment by aredridel** [comment]
I meant the `paypal-rest-sdk` 0.6. It's had a major version bump.

**Comment by grawk** [comment]
ha. duh.

**Comment by grawk** [comment]
We are using the `paypal.payment.create` method only:
https://github.com/krakenjs/kraken-example-with-shoppingcart/blob/master/controllers/pay/index.js#L61

No change to this is mentioned here:
https://github.com/paypal/PayPal-node-SDK/blob/master/release_notes.md#breaking-changes

**Comment by aredridel** [comment]
LGTM then!

**Comment by grawk** [comment]
:+1:

**Pull request merged**
