### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by grawk**
A couple additions over @jugend 's PR #7

### CODE REVIEW

**Comment by aredridel** [comment]
Shiny

**Comment by aredridel** [comment]
(Just fyi, if a PR that amends another PR gets merged, the other one is marked merged too -- so #7 would show merged if it were open once this one is)

**Comment by grawk** [comment]
Oh ok. Thanks :) let me try that..

**Comment by aredridel** [comment]
Nice!

**Pull request merged**
