### PR TITLE
To.react

### PR DESCRIPTION
**Pull request by grawk**
- convert to react usage
- remove dust/makara/localizr/requirejs
- fix delete functionality

### CODE REVIEW

**Comment by shaunwarman** [comment]
I see `account.jsx` being pulled in, but I don't see that file. I also see `cart.jsx`, but I don't think it is used.

**Comment by grawk** [comment]
@shaunwarman account.jsx (and references) need to be removed. I must have some un-pushed deletions. `cart.jsx` is called by `react-engine` when `res.render('cart'...` is called.

**Comment by shaunwarman** [comment]
Ah, perfect. Everything else looks good. 👍

**Comment by grawk** [comment]
Thanks @shaunwarman. I'm waiting on the "content loader" file to be implemented as an npm module (`anemone`) and then i'll push ahead with wanting a merge.

**Comment by samsel** [comment]
👍

**Pull request merged**
